{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "connection": "AgCyKZetF8K8HybqcKrofiQ5USkhIM5tiFcQ3xMzoHVCmmoczVWc6qDY3T60nRnm+vlILNy05xDpMkD/G3n46Npcz+fk+IuaX3lVg/9AJ6h2hGfQBr6gEZyf+nu71zxIvKQDK/1vRXRMIElY2s3cPFunyLS4L5RE7uOlJl3IFgk4Prc97DbVESr4zhSHtm+D1IWvPpyw0GM879kTwsuUpN4qr9CPGcdSUod+nV6J1ZF6rBIZby5vzYC9EcibLgunAer7W+prj5yXGhTCiQX1EtVkYZRcNsUfkFWItIgpWFD45hvIkBIEKCrGsnSGkZU0UclYrxGVGUabxhYK6pKqF+J512XziC3ikVrf5xg70jFUBtBJxqYe7fAiRJm5+HEfVgsaTzFhjqx8otysYOVRC8LgY8sAg/s9rSshj6TY2h3SHLS6PDxMgOBrGW70XzpFadlKEu1i0x13uBAp7lKYQwD+YBa6h4uIHpuekWYCfcbJZ+eDl37nU74Mljo55RHIhOTZIGH3SO+iKgY3jkLAMJfrNTNxzad3gj1g8S72aGFQX9Dsfzy9DZp4hiKsfnezADueMXX+J7bD4XEAhFLll+axYbo31nTZOr88qfG63f/PWMJT/lPSP1KPU2xuie4R9DkttEwuGGDH1Aq4KUC3wvbaMdd0iIWjCOzZWfq6c0p6/A5cxdrmRq3vf2Yp9yf3ErCRTbfNxX9OAnWplaIzD3rckG1Qsq37ZIl1ugSFKSD2LL4=",
      "password": "AgBGMgXNeeNMqTonSeQqb0Uu+B25zW9O7EqRCM0R73KgEqeLj11ILY0wZqAz4ivQrIhcHIFSnnHovf6RuDQ1Oqp0Hvw0SblNM0B2rcDhASLEgKPye5WvzXlaTqgpPtE6T/XUa0MWBkUw7wPrtuGEkE/MtQP8N7qeY1lqbqsBzassonqCKGpuJARDQVyGZj9h8cCtIy6+2XJPSTsThMm7/gdnNRqRXr6HPkw2DHWeD3bgpkcOc881equOjWZVML0Sjj4HfrrrmnrvGh3vHg+RXAJcKf5sfzuXcZqOMuQe3CZQouA7S1ZiFXMecBqG2jfC+dTJNtKLVWrxaw+5SHm3TTi0cAW9xDjG8zelTzGJ9zjNhjdgLCDEVq4y4IzPs+IsJKqmj70wG6ye+GMkT6vNEgEGRStXKuEJ31UxcMLRGfeO3pRHMlenVykCjNGPEKEZRmoPy5EtqgoOg2/5TRkDkFyA2/Vdg3lsgEjimhzRoBNzpQgQ3CSdlFjI4Tx+LzoWvlTxd2FyiukqIJRA1hEjSUgjl59jvKmW2m7Smzw9Lx3Co0iu/ZLWDUe73a/xOOTaN1H99yNux3Cuv5yGEaTsSKA+B+J9PPAhJBIV2abuidXKxoqIYzoXeuVYutVS4NEuvpvD9v+wusZSlwdxO0Cc/m/dfGLVnIYzqMrKc14azV1wuNysgJ95v5pQNro5C5PbXRIBllnweHaIXLmZp4Q+l70=",
      "username": "AgBQUyhWVJeIIipvTIu/79EdLlXYqk/cSnoAhNe95BPIfZlQWDtx/lUgIlUyxayOdVMMHmwIVHnwj6yJAz0zk3d2o8uxkmvDKy/rD9mHiuOSAW5UUOgAgnR//LcMrt16wLk2ZkUVKtkCmuunxqzynKs+l8eCE4b/EeObxPepa0unxZi+w/zArGBxtIo88enHB254zAfL3VfvD/4JB6oDZP+yNO7Elidhr/CuG0KjMM085Q7/TrgTLHv1gnnFt2A6A73ScdWGhSx/gxcBlkxAbuZB8Rk7iFh14W7yGn37ovq8b1cYsNyQyt4UkfjrD12m5clctcpMLx5SOalTNqX6hiZuzaG/xhd7bX6dNXVDDFUFhc31QYMZf33ODf/Ca+3uObQmXZBFu4fST6OvP967Ck1vnyZnNX9kRX0XtSoIPtP649I/AuFFVH3hUnsqVGK9Bj691hcZGdy+A9cPRU1EcPwKxljabk3lmpuatIUdlIQkUfy7qA6lZZlEVwc1DkUuxPQNcVFXn+9yl77inxulQbBuQX4eO+B3hmrrrTB21bBnQwEzkgXY5rpFnWWEjI4xmTvO6mASu1kmYo/c+MQIVrefsqZFpfxPUkqzbRvkOi5gufzqLe8hhhVz9665WGcsSri+VPMICBH3c9eXPM0j5IatRCNdd64fcY9ncgFavCfVvhhqKNCuxyiVW6Cj2FugJJ+yhhFYRe4TDH9o8w=="
    }
  }
}
